package com.example.music

object AbdullahLibrary {
    val songs = listOf(
        Sheelah("طواريك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_1, R.drawable.icon_artist_abdullah, "03:45"),
        Sheelah("ياخذني الشوق", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_2, R.drawable.icon_artist_abdullah, "03:51"),
        Sheelah("جاري الأنتظار", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_3, R.drawable.icon_artist_abdullah, "03:59"),
        Sheelah("اذكريني", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_4, R.drawable.icon_artist_abdullah, "03:31"),
        Sheelah("ملامح", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_5, R.drawable.icon_artist_abdullah, "03:44"),
        Sheelah("يجذبني الزين", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_6, R.drawable.icon_artist_abdullah, "02:56"),
        Sheelah("بعد الكون", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_7, R.drawable.icon_artist_abdullah, "03:52"),
        Sheelah("الراية سعودية", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_8, R.drawable.icon_artist_abdullah, "03:22"),
        Sheelah("ماكنا حبايب", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_9, R.drawable.icon_artist_abdullah, "04:12"),
        Sheelah("ودلي شوقي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_10, R.drawable.icon_artist_abdullah, "03:29"),
        Sheelah("جرح الجفا", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_11, R.drawable.icon_artist_abdullah, "04:30"),
        Sheelah("اكذب عليك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_12, R.drawable.icon_artist_abdullah, "04:08"),
        Sheelah("وين رايح", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_13, R.drawable.icon_artist_abdullah, "03:50"),
        Sheelah("العبوا واطربوا", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_14, R.drawable.icon_artist_abdullah, "03:02"),
        Sheelah("ياجمالك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_15, R.drawable.icon_artist_abdullah, "04:24"),
        Sheelah("ترمي سهم", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_16, R.drawable.icon_artist_abdullah, "04:43"),
        Sheelah("دبي الجميلة", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_17, R.drawable.icon_artist_abdullah, "03:32"),
        Sheelah("وينها", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_18, R.drawable.icon_artist_abdullah, "04:20"),
        Sheelah("علموه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_19, R.drawable.icon_artist_abdullah, "03:22"),
        Sheelah("وعدتيني", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_20, R.drawable.icon_artist_abdullah, "04:09"),
        Sheelah("السعودي قدها", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_21, R.drawable.icon_artist_abdullah, "04:11"),
        Sheelah("الحب مره", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_22, R.drawable.icon_artist_abdullah, "04:30"),
        Sheelah("فرقاك خيره", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_23, R.drawable.icon_artist_abdullah, "02:53"),
        Sheelah("من قدك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_24, R.drawable.icon_artist_abdullah, "03:47"),
        Sheelah("من الغلطان", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_25, R.drawable.icon_artist_abdullah, "04:06"),
        Sheelah("فاقدك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_26, R.drawable.icon_artist_abdullah, "04:48"),
        Sheelah("خط أحمر", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_27, R.drawable.icon_artist_abdullah, "05:00"),
        Sheelah("جعلك على القوة", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_28, R.drawable.icon_artist_abdullah, "03:10"),
        Sheelah("الحب افعال", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_29, R.drawable.icon_artist_abdullah, "03:15"),
        Sheelah("أعد الثواني", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_30, R.drawable.icon_artist_abdullah, "04:15"),
        Sheelah("أتركني أهواك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_31, R.drawable.icon_artist_abdullah, "03:51"),
        Sheelah("غيبتك لاتعيدها", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_32, R.drawable.icon_artist_abdullah, "04:43"),
        Sheelah("مطلوب", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_33, R.drawable.icon_artist_abdullah, "02:58"),
        Sheelah("أغار عليك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_34, R.drawable.icon_artist_abdullah, "03:35"),
        Sheelah("غلطة بحياتي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_35, R.drawable.icon_artist_abdullah, "03:42"),
        Sheelah("عايد علي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_36, R.drawable.icon_artist_abdullah, "03:21"),
        Sheelah("الغياب المر", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_37, R.drawable.icon_artist_abdullah, "04:10"),
        Sheelah("محطات الأمل", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_38, R.drawable.icon_artist_abdullah, "03:33"),
        Sheelah("ان كنت ناسي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_39, R.drawable.icon_artist_abdullah, "04:04"),
        Sheelah("سر العاطفة", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_40, R.drawable.icon_artist_abdullah, "03:54"),
        Sheelah("لو ناوي تهجرني", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_41, R.drawable.icon_artist_abdullah, "03:08"),
        Sheelah("ضيعت داري", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_42, R.drawable.icon_artist_abdullah, "04:47"),
        Sheelah("ماكو ثقه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_43, R.drawable.icon_artist_abdullah, "03:44"),
        Sheelah("طلتك فنانة", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_44, R.drawable.icon_artist_abdullah, "04:14"),
        Sheelah("الراية الخضراء", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_45, R.drawable.icon_artist_abdullah, "04:37"),
        Sheelah("عانيت", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_46, R.drawable.icon_artist_abdullah, "03:35"),
        Sheelah("أحتريك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_47, R.drawable.icon_artist_abdullah, "03:58"),
        Sheelah("ماكسرني", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_48, R.drawable.icon_artist_abdullah, "04:39"),
        Sheelah("حسره", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_49, R.drawable.icon_artist_abdullah, "04:02"),
        Sheelah("انت صدمه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_50, R.drawable.icon_artist_abdullah, "05:17"),
        Sheelah("فرصة أخيرة", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_51, R.drawable.icon_artist_abdullah, "04:19"),
        Sheelah("اسمعني لو مره", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_52, R.drawable.icon_artist_abdullah, "03:23"),
        Sheelah("اروح انا فدوه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_53, R.drawable.icon_artist_abdullah, "04:24"),
        Sheelah("الحنين يفوز", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_54, R.drawable.icon_artist_abdullah, "05:21"),
        Sheelah("أشكر جمالك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_55, R.drawable.icon_artist_abdullah, "04:55"),
        Sheelah("وش غيرك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_56, R.drawable.icon_artist_abdullah, "04:00"),
        Sheelah("جرح فرقاه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_57, R.drawable.icon_artist_abdullah, "03:41"),
        Sheelah("ديار السلاطين", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_58, R.drawable.icon_artist_abdullah, "02:44"),
        Sheelah("خساره فيك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_59, R.drawable.icon_artist_abdullah, "04:57"),
        Sheelah("حالته صعبه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_60, R.drawable.icon_artist_abdullah, "04:07"),
        Sheelah("السعودي قمة", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_61, R.drawable.icon_artist_abdullah, "05:31"),
        Sheelah("طاري غيابك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_62, R.drawable.icon_artist_abdullah, "04:55"),
        Sheelah("تعآل أحضّني", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_63, R.drawable.icon_artist_abdullah, "03:26"),
        Sheelah("وضعي الله لا يوريك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_64, R.drawable.icon_artist_abdullah, "04:43"),
        Sheelah("جعلني فدوه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_65, R.drawable.icon_artist_abdullah, "03:08"),
        Sheelah("عشرة الكذاب", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_66, R.drawable.icon_artist_abdullah, "03:18"),
        Sheelah("وجه الرضا", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_67, R.drawable.icon_artist_abdullah, "03:31"),
        Sheelah("حظر التجول", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_68, R.drawable.icon_artist_abdullah, "03:44"),
        Sheelah("يسبق بي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_69, R.drawable.icon_artist_abdullah, "02:29"),
        Sheelah("الجنوبي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_70, R.drawable.icon_artist_abdullah, "03:39"),
        Sheelah("غلطت وهويتك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_71, R.drawable.icon_artist_abdullah, "04:29"),
        Sheelah("اسين ياقلبي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_72, R.drawable.icon_artist_abdullah, "03:05"),
        Sheelah("إماراتي أنا", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_73, R.drawable.icon_artist_abdullah, "03:26"),
        Sheelah("ليّن العود", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_74, R.drawable.icon_artist_abdullah, "04:25"),
        Sheelah("عزلتي أرحم", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_75, R.drawable.icon_artist_abdullah, "04:07"),
        Sheelah("رمز الفخر", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_76, R.drawable.icon_artist_abdullah, "04:15"),
        Sheelah("ايدي على قلبي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_77, R.drawable.icon_artist_abdullah, "02:56"),
        Sheelah("رحالة الأمارات", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_78, R.drawable.icon_artist_abdullah, "03:19"),
        Sheelah("اشواقي حريقه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_79, R.drawable.icon_artist_abdullah, "03:51"),
        Sheelah("على كيفك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_80, R.drawable.icon_artist_abdullah, "03:50"),
        Sheelah("ذرب وسحاوي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_81, R.drawable.icon_artist_abdullah, "04:30"),
        Sheelah("تردك ظروفك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_82, R.drawable.icon_artist_abdullah, "04:29"),
        Sheelah("يامنور القاعة", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_83, R.drawable.icon_artist_abdullah, "04:41"),
        Sheelah("الخط مشغول", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_84, R.drawable.icon_artist_abdullah, "04:26"),
        Sheelah("سلام ياسيدي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_85, R.drawable.icon_artist_abdullah, "05:13"),
        Sheelah("جرح المعنى", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_86, R.drawable.icon_artist_abdullah, "03:57"),
        Sheelah("هذا وطنّا", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_87, R.drawable.icon_artist_abdullah, "05:49"),
        Sheelah("أغلى ملك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_88, R.drawable.icon_artist_abdullah, "03:42"),
        Sheelah("يامجرم", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_89, R.drawable.icon_artist_abdullah, "05:31"),
        Sheelah("ياهل العوجاء", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_90, R.drawable.icon_artist_abdullah, "05:40"),
        Sheelah("وش أخبارك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_91, R.drawable.icon_artist_abdullah, "05:17"),
        Sheelah("صوبت قلبي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_92, R.drawable.icon_artist_abdullah, "06:51"),
        Sheelah("عبدالله آل مخلص", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_93, R.drawable.icon_artist_abdullah, "02:15"),
        Sheelah("أبطيت عنه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_94, R.drawable.icon_artist_abdullah, "04:40"),
        Sheelah("شيلة مركزي قدام", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_95, R.drawable.icon_artist_abdullah, "04:05"),
        Sheelah("لاتحدانا", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_96, R.drawable.icon_artist_abdullah, "04:21"),
        Sheelah("يهدد حياتي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_97, R.drawable.icon_artist_abdullah, "06:26"),
        Sheelah("قلبي المجروح", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_98, R.drawable.icon_artist_abdullah, "02:18"),
        Sheelah("الهمم", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_99, R.drawable.icon_artist_abdullah, "04:14"),
        Sheelah("ساري الليلة", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_100, R.drawable.icon_artist_abdullah, "07:13"),
        Sheelah("بحر الاشواق", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_101, R.drawable.icon_artist_abdullah, "02:11"),
        Sheelah("الخوي يبشر بعزه", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_102, R.drawable.icon_artist_abdullah, "04:28"),
        Sheelah("ياوطنا فوق", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_103, R.drawable.icon_artist_abdullah, "03:33"),
        Sheelah("احي الخفوق", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_104, R.drawable.icon_artist_abdullah, "05:26"),
        Sheelah("هو صدق انت تحبني", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_105, R.drawable.icon_artist_abdullah, "06:49"),
        Sheelah("شوقي لخلي", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_106, R.drawable.icon_artist_abdullah, "06:36"),
        Sheelah("وين الحب", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_107, R.drawable.icon_artist_abdullah, "05:36"),
        Sheelah("اخر فراق", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_108, R.drawable.icon_artist_abdullah, "03:12"),
        Sheelah("اسمك مزين حروفك", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_109, R.drawable.icon_artist_abdullah, "06:49"),
        Sheelah("طلة الابداع", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_110, R.drawable.icon_artist_abdullah, "06:53"),
        Sheelah("ليه الاهمال", "عبدالله آل مخلص", R.raw.abdullahmokhles_sheelah_111, R.drawable.icon_artist_abdullah, "07:37")
    )
}