package com.example.music

object AlfarwanLibrary {
    val songs = listOf(
        Sheelah("اشوفك وطن", "عبدالله آل فروان", R.raw.alfarwan_sheelah_1, R.drawable.icon_artist_alfarwan, "04:17"),
        Sheelah("لحظة لقاك", "عبدالله آل فروان", R.raw.alfarwan_sheelah_2, R.drawable.icon_artist_alfarwan, "03:48"),
        Sheelah("كنت الحبيب", "عبدالله آل فروان", R.raw.alfarwan_sheelah_3, R.drawable.icon_artist_alfarwan, "04:59"),
        Sheelah("وينك بس؟", "عبدالله آل فروان", R.raw.alfarwan_sheelah_4, R.drawable.icon_artist_alfarwan, "04:34"),
        Sheelah("أنا آسف", "عبدالله آل فروان", R.raw.alfarwan_sheelah_5, R.drawable.icon_artist_alfarwan, "04:01"),
        Sheelah("يكفي ثلاث سنين", "عبدالله آل فروان", R.raw.alfarwan_sheelah_6, R.drawable.icon_artist_alfarwan, "05:25"),
        Sheelah("روحي فدا له", "عبدالله آل فروان", R.raw.alfarwan_sheelah_7, R.drawable.icon_artist_alfarwan, "04:42"),
        Sheelah("لاتطول بالغياب", "عبدالله آل فروان", R.raw.alfarwan_sheelah_8, R.drawable.icon_artist_alfarwan, "03:29"),
        Sheelah("طواري الشوق", "عبدالله آل فروان", R.raw.alfarwan_sheelah_9, R.drawable.icon_artist_alfarwan, "03:59"),
        Sheelah("صمت الغياب", "عبدالله آل فروان", R.raw.alfarwan_sheelah_10, R.drawable.icon_artist_alfarwan, "04:37"),
        Sheelah("رسمتك شوق", "عبدالله آل فروان", R.raw.alfarwan_sheelah_11, R.drawable.icon_artist_alfarwan, "04:35"),
        Sheelah("عمر ثاني", "عبدالله آل فروان", R.raw.alfarwan_sheelah_12, R.drawable.icon_artist_alfarwan, "03:29"),
        Sheelah("الظروف أكبر", "عبدالله آل فروان", R.raw.alfarwan_sheelah_13, R.drawable.icon_artist_alfarwan, "04:08"),
        Sheelah("غير حياتي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_14, R.drawable.icon_artist_alfarwan, "03:05"),
        Sheelah("فيك هايم", "عبدالله آل فروان", R.raw.alfarwan_sheelah_15, R.drawable.icon_artist_alfarwan, "04:18"),
        Sheelah("تزهر أشواقي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_16, R.drawable.icon_artist_alfarwan, "05:31"),
        Sheelah("جمالك غير", "عبدالله آل فروان", R.raw.alfarwan_sheelah_17, R.drawable.icon_artist_alfarwan, "05:45"),
        Sheelah("قسى قلبي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_18, R.drawable.icon_artist_alfarwan, "04:13"),
        Sheelah("آمر تدلل", "عبدالله آل فروان", R.raw.alfarwan_sheelah_19, R.drawable.icon_artist_alfarwan, "03:45"),
        Sheelah("يامبتسم", "عبدالله آل فروان", R.raw.alfarwan_sheelah_20, R.drawable.icon_artist_alfarwan, "03:27"),
        Sheelah("اسسوها رجالها", "عبدالله آل فروان", R.raw.alfarwan_sheelah_21, R.drawable.icon_artist_alfarwan, "03:33"),
        Sheelah("حلوه ذيك الأيام", "عبدالله آل فروان", R.raw.alfarwan_sheelah_22, R.drawable.icon_artist_alfarwan, "04:10"),
        Sheelah("مركب هوانا", "عبدالله آل فروان", R.raw.alfarwan_sheelah_23, R.drawable.icon_artist_alfarwan, "04:45"),
        Sheelah("خيبة آمال", "عبدالله آل فروان", R.raw.alfarwan_sheelah_24, R.drawable.icon_artist_alfarwan, "04:50"),
        Sheelah("الظروف اوهام", "عبدالله آل فروان", R.raw.alfarwan_sheelah_25, R.drawable.icon_artist_alfarwan, "04:35"),
        Sheelah("يوم ميلادي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_26, R.drawable.icon_artist_alfarwan, "05:00"),
        Sheelah("انا الغلطان", "عبدالله آل فروان", R.raw.alfarwan_sheelah_27, R.drawable.icon_artist_alfarwan, "05:33"),
        Sheelah("قفل الموضوع", "عبدالله آل فروان", R.raw.alfarwan_sheelah_28, R.drawable.icon_artist_alfarwan, "05:40"),
        Sheelah("سكه مجهولة", "عبدالله آل فروان", R.raw.alfarwan_sheelah_29, R.drawable.icon_artist_alfarwan, "04:16"),
        Sheelah("أحبك للأبد", "عبدالله آل فروان", R.raw.alfarwan_sheelah_30, R.drawable.icon_artist_alfarwan, "03:57"),
        Sheelah("أقفيت عني", "عبدالله آل فروان", R.raw.alfarwan_sheelah_31, R.drawable.icon_artist_alfarwan, "03:21"),
        Sheelah("تعبت اشتاق", "عبدالله آل فروان", R.raw.alfarwan_sheelah_32, R.drawable.icon_artist_alfarwan, "03:40"),
        Sheelah("مع الأسف", "عبدالله آل فروان", R.raw.alfarwan_sheelah_33, R.drawable.icon_artist_alfarwan, "04:41"),
        Sheelah("ناس غداره", "عبدالله آل فروان", R.raw.alfarwan_sheelah_34, R.drawable.icon_artist_alfarwan, "04:09"),
        Sheelah("يابعد ناسي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_35, R.drawable.icon_artist_alfarwan, "04:34"),
        Sheelah("الا ياكبر حظي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_36, R.drawable.icon_artist_alfarwan, "05:29"),
        Sheelah("واحشني صوتك", "عبدالله آل فروان", R.raw.alfarwan_sheelah_37, R.drawable.icon_artist_alfarwan, "03:28"),
        Sheelah("ابتسم لي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_38, R.drawable.icon_artist_alfarwan, "03:25"),
        Sheelah("وافي في حبك", "عبدالله آل فروان", R.raw.alfarwan_sheelah_39, R.drawable.icon_artist_alfarwan, "03:32"),
        Sheelah("بتروح عادي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_40, R.drawable.icon_artist_alfarwan, "03:17"),
        Sheelah("غريبه", "عبدالله آل فروان", R.raw.alfarwan_sheelah_41, R.drawable.icon_artist_alfarwan, "04:55"),
        Sheelah("وش عذرك؟", "عبدالله آل فروان", R.raw.alfarwan_sheelah_42, R.drawable.icon_artist_alfarwan, "04:02"),
        Sheelah("طال الجفى", "عبدالله آل فروان", R.raw.alfarwan_sheelah_43, R.drawable.icon_artist_alfarwan, "03:30"),
        Sheelah("جابك الطاري", "عبدالله آل فروان", R.raw.alfarwan_sheelah_44, R.drawable.icon_artist_alfarwan, "04:21"),
        Sheelah("عشقٍ جديد", "عبدالله آل فروان", R.raw.alfarwan_sheelah_45, R.drawable.icon_artist_alfarwan, "02:23"),
        Sheelah(" ليه الجف", "عبدالله آل فروان", R.raw.alfarwan_sheelah_46, R.drawable.icon_artist_alfarwan, "03:17"),
        Sheelah("توادعني", "عبدالله آل فروان", R.raw.alfarwan_sheelah_47, R.drawable.icon_artist_alfarwan, "03:51"),
        Sheelah("وشلون ترضى؟", "عبدالله آل فروان", R.raw.alfarwan_sheelah_48, R.drawable.icon_artist_alfarwan, "04:07"),
        Sheelah("راضي بحبك", "عبدالله آل فروان", R.raw.alfarwan_sheelah_49, R.drawable.icon_artist_alfarwan, "02:46"),
        Sheelah("لاتزيد الجروح", "عبدالله آل فروان", R.raw.alfarwan_sheelah_50, R.drawable.icon_artist_alfarwan, "04:06"),
        Sheelah("هزتني الذكرى", "عبدالله آل فروان", R.raw.alfarwan_sheelah_51, R.drawable.icon_artist_alfarwan, "03:56"),
        Sheelah("وحدّ المملكة", "عبدالله آل فروان", R.raw.alfarwan_sheelah_52, R.drawable.icon_artist_alfarwan, "04:22"),
        Sheelah("أجمل غرامي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_53, R.drawable.icon_artist_alfarwan, "04:40"),
        Sheelah("أيام عمري", "عبدالله آل فروان", R.raw.alfarwan_sheelah_54, R.drawable.icon_artist_alfarwan, "04:08"),
        Sheelah("ياشين الهجر", "عبدالله آل فروان", R.raw.alfarwan_sheelah_55, R.drawable.icon_artist_alfarwan, "05:06"),
        Sheelah("لبى العيون", "عبدالله آل فروان", R.raw.alfarwan_sheelah_56, R.drawable.icon_artist_alfarwan, "03:21"),
        Sheelah("انا احتاجك", "عبدالله آل فروان", R.raw.alfarwan_sheelah_57, R.drawable.icon_artist_alfarwan, "03:22"),
        Sheelah("خلاني وحيد", "عبدالله آل فروان", R.raw.alfarwan_sheelah_58, R.drawable.icon_artist_alfarwan, "04:58"),
        Sheelah("الغلا وين", "عبدالله آل فروان", R.raw.alfarwan_sheelah_59, R.drawable.icon_artist_alfarwan, "03:04"),
        Sheelah("جرح قديم", "عبدالله آل فروان", R.raw.alfarwan_sheelah_60, R.drawable.icon_artist_alfarwan, "04:03"),
        Sheelah("بسمة حزين", "عبدالله آل فروان", R.raw.alfarwan_sheelah_61, R.drawable.icon_artist_alfarwan, "05:25"),
        Sheelah("أنت وضميرك", "عبدالله آل فروان", R.raw.alfarwan_sheelah_62, R.drawable.icon_artist_alfarwan, "03:15"),
        Sheelah("اوتار العتب", "عبدالله آل فروان", R.raw.alfarwan_sheelah_63, R.drawable.icon_artist_alfarwan, "02:36"),
        Sheelah("انا مشتاق .. والله العظيم", "عبدالله آل فروان", R.raw.alfarwan_sheelah_64, R.drawable.icon_artist_alfarwan, "03:43"),
        Sheelah("لايغيب اتصالك", "عبدالله آل فروان", R.raw.alfarwan_sheelah_65, R.drawable.icon_artist_alfarwan, "03:32"),
        Sheelah("غرام التسلي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_66, R.drawable.icon_artist_alfarwan, "02:43"),
        Sheelah("طريق العاشقين", "عبدالله آل فروان", R.raw.alfarwan_sheelah_67, R.drawable.icon_artist_alfarwan, "03:52"),
        Sheelah("ويش حاجتك", "عبدالله آل فروان", R.raw.alfarwan_sheelah_68, R.drawable.icon_artist_alfarwan, "03:14"),
        Sheelah("ليتك تروف", "عبدالله آل فروان", R.raw.alfarwan_sheelah_69, R.drawable.icon_artist_alfarwan, "04:45"),
        Sheelah("انت نصيبي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_70, R.drawable.icon_artist_alfarwan, "03:54"),
        Sheelah("ال فروان هل العز", "عبدالله آل فروان", R.raw.alfarwan_sheelah_71, R.drawable.icon_artist_alfarwan, "04:36"),
        Sheelah("سير علينا", "عبدالله آل فروان", R.raw.alfarwan_sheelah_72, R.drawable.icon_artist_alfarwan, "06:40"),
        Sheelah("ال معجبه الدواهى", "عبدالله آل فروان", R.raw.alfarwan_sheelah_73, R.drawable.icon_artist_alfarwan, "07:25"),
        Sheelah("نخوة قبيلة يام", "عبدالله آل فروان", R.raw.alfarwan_sheelah_74, R.drawable.icon_artist_alfarwan, "04:23"),
        Sheelah("السهر والشوق", "عبدالله آل فروان", R.raw.alfarwan_sheelah_75, R.drawable.icon_artist_alfarwan, "02:42"),
        Sheelah("لاتبتعد يابعد روحي", "عبدالله آل فروان", R.raw.alfarwan_sheelah_76, R.drawable.icon_artist_alfarwan, "08:23"),
        Sheelah("يا صاحبي لا تروح", "عبدالله آل فروان", R.raw.alfarwan_sheelah_77, R.drawable.icon_artist_alfarwan, "03:52")
    )
}