package com.example.music

object GhreebLibrary {
    val songs = listOf(
        Sheelah("سحر عيونك", "غريب آل مخلص", R.raw.ghreeb_sheelah_1, R.drawable.icon_artist_ghreeb, "03:03"),
        Sheelah("يازين صبح العيد", "غريب آل مخلص", R.raw.ghreeb_sheelah_2, R.drawable.icon_artist_ghreeb, "03:23"),
        Sheelah("حبيب الروح", "غريب آل مخلص", R.raw.ghreeb_sheelah_3, R.drawable.icon_artist_ghreeb, "03:38"),
        Sheelah("بيرق مملكتنا", "غريب آل مخلص", R.raw.ghreeb_sheelah_4, R.drawable.icon_artist_ghreeb, "04:33"),
        Sheelah("فديت وجهك", "غريب آل مخلص", R.raw.ghreeb_sheelah_5, R.drawable.icon_artist_ghreeb, "03:37"),
        Sheelah("احلى عيون", "غريب آل مخلص", R.raw.ghreeb_sheelah_6, R.drawable.icon_artist_ghreeb, "04:05"),
        Sheelah("على طاريك", "غريب آل مخلص", R.raw.ghreeb_sheelah_7, R.drawable.icon_artist_ghreeb, "04:30"),
        Sheelah("أمي", "غريب آل مخلص", R.raw.ghreeb_sheelah_8, R.drawable.icon_artist_ghreeb, "04:32"),
        Sheelah("انتهت قصة غرامك", "غريب آل مخلص", R.raw.ghreeb_sheelah_9, R.drawable.icon_artist_ghreeb, "04:15"),
        Sheelah("اكبر توهيقه", "غريب آل مخلص", R.raw.ghreeb_sheelah_10, R.drawable.icon_artist_ghreeb, "03:36"),
        Sheelah("ليت المطر يسقيني", "غريب آل مخلص", R.raw.ghreeb_sheelah_11, R.drawable.icon_artist_ghreeb, "03:56"),
        Sheelah("فتنة الشرق والشام", "غريب آل مخلص", R.raw.ghreeb_sheelah_12, R.drawable.icon_artist_ghreeb, "03:55"),
        Sheelah("اسم المحبه", "غريب آل مخلص", R.raw.ghreeb_sheelah_13, R.drawable.icon_artist_ghreeb, "04:09"),
        Sheelah("بحر شوقك", "غريب آل مخلص", R.raw.ghreeb_sheelah_14, R.drawable.icon_artist_ghreeb, "03:51"),
        Sheelah("تكلم", "غريب آل مخلص", R.raw.ghreeb_sheelah_15, R.drawable.icon_artist_ghreeb, "04:36"),
        Sheelah("أنت ماشاء الله", "غريب آل مخلص", R.raw.ghreeb_sheelah_16, R.drawable.icon_artist_ghreeb, "05:39"),
        Sheelah("الوطن غالي", "غريب آل مخلص", R.raw.ghreeb_sheelah_17, R.drawable.icon_artist_ghreeb, "03:53"),
        Sheelah("خذاني الشوق", "غريب آل مخلص", R.raw.ghreeb_sheelah_18, R.drawable.icon_artist_ghreeb, "03:26"),
        Sheelah("العزله احسن", "غريب آل مخلص", R.raw.ghreeb_sheelah_19, R.drawable.icon_artist_ghreeb, "04:16"),
        Sheelah("حظ سلساله", "غريب آل مخلص", R.raw.ghreeb_sheelah_20, R.drawable.icon_artist_ghreeb, "02:51"),
        Sheelah("سيد العشاق", "غريب آل مخلص", R.raw.ghreeb_sheelah_21, R.drawable.icon_artist_ghreeb, "04:22"),
        Sheelah("العشق يجمعنا", "غريب آل مخلص", R.raw.ghreeb_sheelah_22, R.drawable.icon_artist_ghreeb, "04:08"),
        Sheelah("المفارق سنه", "غريب آل مخلص", R.raw.ghreeb_sheelah_23, R.drawable.icon_artist_ghreeb, "03:29"),
        Sheelah("أنت معذور", "غريب آل مخلص", R.raw.ghreeb_sheelah_24, R.drawable.icon_artist_ghreeb, "03:55"),
        Sheelah("حب دايم", "غريب آل مخلص", R.raw.ghreeb_sheelah_25, R.drawable.icon_artist_ghreeb, "04:02"),
        Sheelah("فتنة عيونك", "غريب آل مخلص", R.raw.ghreeb_sheelah_26, R.drawable.icon_artist_ghreeb, "04:10"),
        Sheelah("رمضان يارمضان", "غريب آل مخلص", R.raw.ghreeb_sheelah_27, R.drawable.icon_artist_ghreeb, "03:16"),
        Sheelah("وينها أيامك", "غريب آل مخلص", R.raw.ghreeb_sheelah_28, R.drawable.icon_artist_ghreeb, "04:05"),
        Sheelah("مامثلك وطن", "غريب آل مخلص", R.raw.ghreeb_sheelah_29, R.drawable.icon_artist_ghreeb, "03:21"),
        Sheelah("سهير العين", "غريب آل مخلص", R.raw.ghreeb_sheelah_30, R.drawable.icon_artist_ghreeb, "03:55"),
        Sheelah("النفسيه", "غريب آل مخلص", R.raw.ghreeb_sheelah_31, R.drawable.icon_artist_ghreeb, "05:28"),
        Sheelah("هذي الدنيا", "غريب آل مخلص", R.raw.ghreeb_sheelah_32, R.drawable.icon_artist_ghreeb, "05:30"),
        Sheelah("راعي الهوى", "غريب آل مخلص", R.raw.ghreeb_sheelah_33, R.drawable.icon_artist_ghreeb, "02:58"),
        Sheelah("حبك وهم", "غريب آل مخلص", R.raw.ghreeb_sheelah_34, R.drawable.icon_artist_ghreeb, "04:04"),
        Sheelah("اهرب بي", "غريب آل مخلص", R.raw.ghreeb_sheelah_35, R.drawable.icon_artist_ghreeb, "03:45"),
        Sheelah("حي بسماتك", "غريب آل مخلص", R.raw.ghreeb_sheelah_36, R.drawable.icon_artist_ghreeb, "03:52"),
        Sheelah("الوصل مقطوع", "غريب آل مخلص", R.raw.ghreeb_sheelah_37, R.drawable.icon_artist_ghreeb, "04:40"),
        Sheelah("أبغاه الحين", "غريب آل مخلص", R.raw.ghreeb_sheelah_38, R.drawable.icon_artist_ghreeb, "03:55"),
        Sheelah("ترجيتك تروف", "غريب آل مخلص", R.raw.ghreeb_sheelah_39, R.drawable.icon_artist_ghreeb, "03:41"),
        Sheelah("فرصة سعيدة", "غريب آل مخلص", R.raw.ghreeb_sheelah_40, R.drawable.icon_artist_ghreeb, "04:25"),
        Sheelah("هويتك", "غريب آل مخلص", R.raw.ghreeb_sheelah_41, R.drawable.icon_artist_ghreeb, "03:38"),
        Sheelah("ولاتزعل", "غريب آل مخلص", R.raw.ghreeb_sheelah_42, R.drawable.icon_artist_ghreeb, "03:15"),
        Sheelah("لاتعذر بالظروف", "غريب آل مخلص", R.raw.ghreeb_sheelah_43, R.drawable.icon_artist_ghreeb, "04:56"),
        Sheelah("ياروح الروح", "غريب آل مخلص", R.raw.ghreeb_sheelah_44, R.drawable.icon_artist_ghreeb, "02:58"),
        Sheelah("خيبه", "غريب آل مخلص", R.raw.ghreeb_sheelah_45, R.drawable.icon_artist_ghreeb, "04:37"),
        Sheelah("غيرك مايعنيني", "غريب آل مخلص", R.raw.ghreeb_sheelah_46, R.drawable.icon_artist_ghreeb, "03:45"),
        Sheelah("منك مجروح", "غريب آل مخلص", R.raw.ghreeb_sheelah_47, R.drawable.icon_artist_ghreeb, "05:10"),
        Sheelah("هو فيه غيرك", "غريب آل مخلص", R.raw.ghreeb_sheelah_48, R.drawable.icon_artist_ghreeb, "04:31"),
        Sheelah("لاتعتذر", "غريب آل مخلص", R.raw.ghreeb_sheelah_49, R.drawable.icon_artist_ghreeb, "04:08"),
        Sheelah("زينك جديد", "غريب آل مخلص", R.raw.ghreeb_sheelah_50, R.drawable.icon_artist_ghreeb, "03:39"),
        Sheelah("عذبت حالي", "غريب آل مخلص", R.raw.ghreeb_sheelah_51, R.drawable.icon_artist_ghreeb, "04:00"),
        Sheelah("الله يسهل طريقه", "غريب آل مخلص", R.raw.ghreeb_sheelah_52, R.drawable.icon_artist_ghreeb, "03:09"),
        Sheelah("أغلى بشر", "غريب آل مخلص", R.raw.ghreeb_sheelah_53, R.drawable.icon_artist_ghreeb, "03:40"),
        Sheelah("لاتحرمني من عيونك", "غريب آل مخلص", R.raw.ghreeb_sheelah_54, R.drawable.icon_artist_ghreeb, "02:52"),
        Sheelah("البعد موتي", "غريب آل مخلص", R.raw.ghreeb_sheelah_55, R.drawable.icon_artist_ghreeb, "04:07"),
        Sheelah("تجرحني وأحبك", "غريب آل مخلص", R.raw.ghreeb_sheelah_56, R.drawable.icon_artist_ghreeb, "04:41"),
        Sheelah("راح ونساني", "غريب آل مخلص", R.raw.ghreeb_sheelah_57, R.drawable.icon_artist_ghreeb, "03:48"),
        Sheelah("أنساك لحظة", "غريب آل مخلص", R.raw.ghreeb_sheelah_58, R.drawable.icon_artist_ghreeb, "03:54"),
        Sheelah("عشير الروح", "غريب آل مخلص", R.raw.ghreeb_sheelah_59, R.drawable.icon_artist_ghreeb, "03:59"),
        Sheelah("زين وحلا", "غريب آل مخلص", R.raw.ghreeb_sheelah_60, R.drawable.icon_artist_ghreeb, "04:52"),
        Sheelah("حزين من جدي", "غريب آل مخلص", R.raw.ghreeb_sheelah_61, R.drawable.icon_artist_ghreeb, "04:26"),
        Sheelah("جعلني ماخلا", "غريب آل مخلص", R.raw.ghreeb_sheelah_62, R.drawable.icon_artist_ghreeb, "03:16"),
        Sheelah("سلموا لي", "غريب آل مخلص", R.raw.ghreeb_sheelah_63, R.drawable.icon_artist_ghreeb, "03:33"),
        Sheelah("مالها إلا الفراق", "غريب آل مخلص", R.raw.ghreeb_sheelah_64, R.drawable.icon_artist_ghreeb, "04:38"),
        Sheelah("عزاز النفوس", "غريب آل مخلص", R.raw.ghreeb_sheelah_65, R.drawable.icon_artist_ghreeb, "04:12"),
        Sheelah("رسايل العشاق", "غريب آل مخلص", R.raw.ghreeb_sheelah_66, R.drawable.icon_artist_ghreeb, "04:05"),
        Sheelah("اعاتبه برفوق", "غريب آل مخلص", R.raw.ghreeb_sheelah_67, R.drawable.icon_artist_ghreeb, "02:24"),
        Sheelah("بعت الحبيب", "غريب آل مخلص", R.raw.ghreeb_sheelah_68, R.drawable.icon_artist_ghreeb, "03:39"),
        Sheelah("يوم الوداع", "غريب آل مخلص", R.raw.ghreeb_sheelah_69, R.drawable.icon_artist_ghreeb, "05:32"),
        Sheelah("لبى العرب ياعرب", "غريب آل مخلص", R.raw.ghreeb_sheelah_70, R.drawable.icon_artist_ghreeb, "03:11"),
        Sheelah("لاتجيب العيد", "غريب آل مخلص", R.raw.ghreeb_sheelah_71, R.drawable.icon_artist_ghreeb, "06:40"),
        Sheelah("لحن الفراق", "غريب آل مخلص", R.raw.ghreeb_sheelah_72, R.drawable.icon_artist_ghreeb, "03:56"),
        Sheelah("أوجعني معك", "غريب آل مخلص", R.raw.ghreeb_sheelah_73, R.drawable.icon_artist_ghreeb, "03:06"),
        Sheelah("ضيعت فكري", "غريب آل مخلص", R.raw.ghreeb_sheelah_74, R.drawable.icon_artist_ghreeb, "02:45"),
        Sheelah("بعد مارحلوا", "غريب آل مخلص", R.raw.ghreeb_sheelah_75, R.drawable.icon_artist_ghreeb, "04:35"),
        Sheelah("ساكت على الجرح", "غريب آل مخلص", R.raw.ghreeb_sheelah_76, R.drawable.icon_artist_ghreeb, "02:50"),
        Sheelah("أطهر ذنوبي", "غريب آل مخلص", R.raw.ghreeb_sheelah_77, R.drawable.icon_artist_ghreeb, "06:14"),
        Sheelah("ماعرف العب", "غريب آل مخلص", R.raw.ghreeb_sheelah_78, R.drawable.icon_artist_ghreeb, "03:51"),
        Sheelah("يتغلى", "غريب آل مخلص", R.raw.ghreeb_sheelah_79, R.drawable.icon_artist_ghreeb, "04:52"),
        Sheelah("ليتك تروف", "غريب آل مخلص", R.raw.ghreeb_sheelah_80, R.drawable.icon_artist_ghreeb, "04:45"),
        Sheelah("اتعب القلب فرقاك", "غريب آل مخلص", R.raw.ghreeb_sheelah_81, R.drawable.icon_artist_ghreeb, "05:02"),
        Sheelah("على العهد باقي", "غريب آل مخلص", R.raw.ghreeb_sheelah_82, R.drawable.icon_artist_ghreeb, "05:56"),
        Sheelah("يالهجر مانبغاك", "غريب آل مخلص", R.raw.ghreeb_sheelah_83, R.drawable.icon_artist_ghreeb, "04:34"),
        Sheelah("سما سما", "غريب آل مخلص", R.raw.ghreeb_sheelah_84, R.drawable.icon_artist_ghreeb, "04:58"),
        Sheelah("شف لك حل", "غريب آل مخلص", R.raw.ghreeb_sheelah_85, R.drawable.icon_artist_ghreeb, "05:40"),
        Sheelah("ليه تجفاني", "غريب آل مخلص", R.raw.ghreeb_sheelah_86, R.drawable.icon_artist_ghreeb, "05:52"),
        Sheelah("زلزلوا الميدان", "غريب آل مخلص", R.raw.ghreeb_sheelah_87, R.drawable.icon_artist_ghreeb, "06:03"),
        Sheelah("أحسبك تمزح", "غريب آل مخلص", R.raw.ghreeb_sheelah_88, R.drawable.icon_artist_ghreeb, "05:04"),
        Sheelah("وين أنت عني", "غريب آل مخلص", R.raw.ghreeb_sheelah_89, R.drawable.icon_artist_ghreeb, "04:52"),
        Sheelah("دق خشم البعيد ودق خشم الموالي", "غريب آل مخلص", R.raw.ghreeb_sheelah_90, R.drawable.icon_artist_ghreeb, "05:39"),
        Sheelah("يامزيون واصلني", "غريب آل مخلص", R.raw.ghreeb_sheelah_91, R.drawable.icon_artist_ghreeb, "04:20"),
        Sheelah("حكم ضميرك", "غريب آل مخلص", R.raw.ghreeb_sheelah_92, R.drawable.icon_artist_ghreeb, "06:11"),
        Sheelah("شيلة قصر الاماني", "غريب آل مخلص", R.raw.ghreeb_sheelah_93, R.drawable.icon_artist_ghreeb, "05:09"),
        Sheelah("من نظرتك يازين", "غريب آل مخلص", R.raw.ghreeb_sheelah_94, R.drawable.icon_artist_ghreeb, "03:45"),
        Sheelah("المفارق تبت يدينه", "غريب آل مخلص", R.raw.ghreeb_sheelah_95, R.drawable.icon_artist_ghreeb, "03:27"),
        Sheelah("ماقدر على الفرقى", "غريب آل مخلص", R.raw.ghreeb_sheelah_96, R.drawable.icon_artist_ghreeb, "06:33"),
        Sheelah("شيلة عزوة آل مخلص", "غريب آل مخلص", R.raw.ghreeb_sheelah_97, R.drawable.icon_artist_ghreeb, "04:37"),
        Sheelah("منوة الروح", "غريب آل مخلص", R.raw.ghreeb_sheelah_98, R.drawable.icon_artist_ghreeb, "03:15")
    )
}